# Generated by Django 5.2.8 on 2025-11-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalarticle',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='legalarticle',
            name='is_constitution',
            field=models.BooleanField(default=False, help_text='Mark if this is the Constitution of Kenya'),
        ),
        migrations.AlterField(
            model_name='legalarticle',
            name='category',
            field=models.CharField(choices=[('constitutional', 'Constitutional Law'), ('criminal', 'Criminal Law'), ('family', 'Family Law'), ('civil', 'Civil Law'), ('rights', 'Human Rights'), ('employment', 'Employment Law'), ('property', 'Property Law')], max_length=50),
        ),
    ]
